info:
  app:
    description: JavaExpress API Gateway MS
    version: 0.0.1
  contact: 88888
spring:
  application:
    name: apigatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
