info:
  app:
    description: JavaExpress Accounts MS
    version: 0.0.1
  contact: 88888
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

server:
  port: 9093
spring:
  application:
    name: accounts
  datasource:
    password: admin
    url: jdbc:h2:mem:accountsdb
    username: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        automatic.transition-from-open-to-half-open-enabled: true