info:
  app:
    description: JavaExpress Accounts MS
    version: 0.0.1
  contact: 88888
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
server:
  port: 9093
spring:
  application:
    name: accounts
  datasource:
    password: admin
    url: jdbc:h2:mem:accountsdb
    username: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
